//
// duk_rhi sample: cube
//
// Demonstrates:
//   - A vertex buffer (position + colour, 8 unique vertices)
//   - An index buffer (36 indices, uint16_t)
//   - A per-frame uniform buffer with MVP matrices passed through ShaderResources
//   - Indexed draw call with a spinning model rotation
//
// NOTE: This sample drives RHI implementation work that does not yet exist:
//   - Descriptor set writing / binding from ShaderResources::uniformBuffers
//   - Depth buffer attachment on the swapchain render pass
//   - Buffer staging for STATIC update-frequency buffers
//

#include <duk_log/logger.h>
#include <duk_log/log.h>
#include <duk_log/sinks/term_color_sink.h>

#include <duk_platform/platform.h>

#include <duk_rhi/instance.h>
#include <duk_rhi/runtime_shader_data_source.h>
#include <duk_rhi/pipeline_state.h>
#include <duk_rhi/index_types.h>

#include <shaderc/shaderc.hpp>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include <chrono>

// -----------------------------------------------------------------------
// GLSL shaders
// -----------------------------------------------------------------------

static const char* kVertexGlsl = R"glsl(
#version 450

layout(location = 0) in vec3 inPosition;
layout(location = 1) in vec3 inColor;

uniform MatricesUBO {
    mat4 model;
    mat4 view;
    mat4 proj;
} matrices;

layout(location = 0) out vec3 fragColor;

void main() {
    gl_Position = matrices.proj * matrices.view * matrices.model * vec4(inPosition, 1.0);
    fragColor   = inColor;
}
)glsl";

static const char* kFragmentGlsl = R"glsl(
#version 450

layout(location = 0) in  vec3 fragColor;
layout(location = 0) out vec4 outColor;

uniform ColorUBO {
    float intensity;
} color;

void main() {
    outColor = vec4(fragColor * color.intensity, 1.0);
}
)glsl";

// -----------------------------------------------------------------------
// Geometry
// -----------------------------------------------------------------------

// 8 corners of a unit cube. Position and colour stored in separate arrays
// so that each maps to its own vertex buffer binding slot, matching the
// per-attribute binding model generated by vertex layout reflection.

static const glm::vec3 kPositions[] = {
    // front face  (z = -0.5)
    {-0.5f, -0.5f,  -0.5f},  // 0
    { 0.5f, -0.5f,  -0.5f},  // 1
    { 0.5f,  0.5f,  -0.5f},  // 2
    {-0.5f,  0.5f,  -0.5f},  // 3
    // back face   (z = 0.5)
    {-0.5f, -0.5f, 0.5f},  // 4
    { 0.5f, -0.5f, 0.5f},  // 5
    { 0.5f,  0.5f, 0.5f},  // 6
    {-0.5f,  0.5f, 0.5f},  // 7
};

static const glm::vec3 kColors[] = {
    {1.0f, 0.0f, 0.0f},  // 0
    {0.0f, 1.0f, 0.0f},  // 1
    {0.0f, 0.0f, 1.0f},  // 2
    {1.0f, 1.0f, 0.0f},  // 3
    {1.0f, 0.0f, 1.0f},  // 4
    {0.0f, 1.0f, 1.0f},  // 5
    {1.0f, 1.0f, 1.0f},  // 6
    {0.5f, 0.5f, 0.5f},  // 7
};

// Counter-clockwise winding (front-face) viewed from outside the cube.
static const uint16_t kIndices[] = {
    0, 1, 2,  2, 3, 0,  // front
    1, 5, 6,  6, 2, 1,  // right
    5, 4, 7,  7, 6, 5,  // back
    4, 0, 3,  3, 7, 4,  // left
    3, 2, 6,  6, 7, 3,  // top
    4, 5, 1,  1, 0, 4,  // bottom
};

static constexpr uint32_t kIndexCount = static_cast<uint32_t>(std::size(kIndices));

// -----------------------------------------------------------------------
// Per-frame uniform data
// -----------------------------------------------------------------------

struct MatricesUBO {
    glm::mat4 model;
    glm::mat4 view;
    glm::mat4 proj;
};

struct ColorUBO {
    float intensity;
};

// -----------------------------------------------------------------------
// GLSL → SPIR-V helper
// -----------------------------------------------------------------------

static std::vector<uint8_t> compile_glsl(const char* source, shaderc_shader_kind kind, const char* debugName) {
    shaderc::Compiler compiler;
    shaderc::CompileOptions options;
    options.SetTargetEnvironment(shaderc_target_env_vulkan, shaderc_env_version_vulkan_1_0);
    options.SetOptimizationLevel(shaderc_optimization_level_zero);
    options.SetAutoBindUniforms(true);
    options.SetAutoMapLocations(true);

    auto result = compiler.CompileGlslToSpv(source, kind, debugName, options);
    if (result.GetCompilationStatus() != shaderc_compilation_status_success) {
        duk::log::fatal("Shader compilation failed ({}): {}", debugName, result.GetErrorMessage());
    }

    const auto* byteBegin = reinterpret_cast<const uint8_t*>(result.cbegin());
    const auto* byteEnd   = reinterpret_cast<const uint8_t*>(result.cend());
    return {byteBegin, byteEnd};
}

int main() {

    // -----------------------------------------------------------------------
    // Window
    // -----------------------------------------------------------------------
    auto platform = duk::platform::create_platform();

    duk::log::instance()->add_sink(std::make_unique<duk::log::TermColorSink>("duk", duk::log::Level::INFO));

    duk::platform::WindowCreateInfo windowCreateInfo = {};
    windowCreateInfo.title  = "duk_rhi - cube";
    windowCreateInfo.width  = 1280;
    windowCreateInfo.height = 720;
    windowCreateInfo.style  = duk::platform::WindowStyle::STANDARD;

    auto window = platform->create_window(windowCreateInfo);

    volatile bool running = true;

    duk::event::Listener listener;
    listener.listen(window->window_close_event,   [&window]  { window->close(); });
    listener.listen(window->window_destroy_event, [&running] { running = false; });
    listener.listen(window->key_event, [&window](duk::platform::Keys key, duk::platform::KeyModifiers::Mask, duk::platform::KeyAction action) {
        if (key == duk::platform::Keys::ESC && action == duk::platform::KeyAction::PRESS) {
            window->close();
        }
    });

    // -----------------------------------------------------------------------
    // RHI device
    // -----------------------------------------------------------------------
    duk::rhi::InstanceCreateInfo rhiCreateInfo = {};
    rhiCreateInfo.applicationName    = "cube_sample";
    rhiCreateInfo.applicationVersion = 1;
    rhiCreateInfo.engineName         = "duk";
    rhiCreateInfo.engineVersion      = 1;
    rhiCreateInfo.api                = duk::rhi::API::VULKAN;
    rhiCreateInfo.validationLayers   = true;
    rhiCreateInfo.deviceIndex        = 0;
    rhiCreateInfo.logger             = duk::log::instance()->default_logger();

    auto rhi = duk::rhi::Instance::create(rhiCreateInfo);

    // -----------------------------------------------------------------------
    // Command context
    // -----------------------------------------------------------------------
    duk::rhi::CommandContextCreateInfo contextCreateInfo = {};
    contextCreateInfo.type           = duk::rhi::CommandQueue::Type::GRAPHICS;
    contextCreateInfo.window         = window.get();
    contextCreateInfo.framesInFlight = 2;
    auto ctx = rhi->create_command_context(contextCreateInfo);

    // -----------------------------------------------------------------------
    // Shader
    // -----------------------------------------------------------------------
    duk::rhi::RuntimeShaderDataSourceCreateInfo shaderSourceCreateInfo = {};
    shaderSourceCreateInfo.vertexShaderCode   = compile_glsl(kVertexGlsl,   shaderc_vertex_shader,   "cube.vert");
    shaderSourceCreateInfo.fragmentShaderCode = compile_glsl(kFragmentGlsl, shaderc_fragment_shader, "cube.frag");
    auto shaderDataSource = duk::rhi::RuntimeShaderDataSource(shaderSourceCreateInfo);

    duk::rhi::ShaderCreateInfo shaderCreateInfo = {};
    shaderCreateInfo.shaderDataSource = &shaderDataSource;

    auto shader = ctx->create_shader(shaderCreateInfo);

    // -----------------------------------------------------------------------
    // Buffers
    // -----------------------------------------------------------------------

    // Position vertex buffer — static, uploaded once at startup.
    duk::rhi::BufferCreateInfo positionBufferCreateInfo = {};
    positionBufferCreateInfo.type            = duk::rhi::Buffer::Type::VERTEX;
    positionBufferCreateInfo.updateFrequency = duk::rhi::Buffer::UpdateFrequency::STATIC;
    positionBufferCreateInfo.size            = sizeof(kPositions);
    auto positionBuffer = ctx->create_buffer(positionBufferCreateInfo);

    // Colour vertex buffer — static, uploaded once at startup.
    duk::rhi::BufferCreateInfo colorBufferCreateInfo = {};
    colorBufferCreateInfo.type            = duk::rhi::Buffer::Type::VERTEX;
    colorBufferCreateInfo.updateFrequency = duk::rhi::Buffer::UpdateFrequency::STATIC;
    colorBufferCreateInfo.size            = sizeof(kColors);
    auto colorBuffer = ctx->create_buffer(colorBufferCreateInfo);

    // Index buffer — static, uploaded once at startup.
    duk::rhi::BufferCreateInfo indexBufferCreateInfo = {};
    indexBufferCreateInfo.type            = duk::rhi::Buffer::Type::INDEX_16;
    indexBufferCreateInfo.updateFrequency = duk::rhi::Buffer::UpdateFrequency::STATIC;
    indexBufferCreateInfo.size            = sizeof(kIndices);
    auto indexBuffer = ctx->create_buffer(indexBufferCreateInfo);

    // Uniform buffer — dynamic, written every frame with the current MVP matrices.
    duk::rhi::BufferCreateInfo uniformBufferCreateInfo = {};
    uniformBufferCreateInfo.type            = duk::rhi::Buffer::Type::UNIFORM;
    uniformBufferCreateInfo.updateFrequency = duk::rhi::Buffer::UpdateFrequency::DYNAMIC;
    uniformBufferCreateInfo.size            = sizeof(MatricesUBO);
    auto matricesUBO = ctx->create_buffer(uniformBufferCreateInfo);

    // Color uniform buffer — dynamic, animated intensity value.
    duk::rhi::BufferCreateInfo colorUniformBufferCreateInfo = {};
    colorUniformBufferCreateInfo.type            = duk::rhi::Buffer::Type::UNIFORM;
    colorUniformBufferCreateInfo.updateFrequency = duk::rhi::Buffer::UpdateFrequency::DYNAMIC;
    colorUniformBufferCreateInfo.size            = sizeof(ColorUBO);
    auto colorUBO = ctx->create_buffer(colorUniformBufferCreateInfo);

    // Upload static mesh data.
    ctx->prepare();
    {
        auto transfer = ctx->transfer();
        transfer.write_buffer(positionBuffer.get(), kPositions, sizeof(kPositions), 0);
        transfer.write_buffer(colorBuffer.get(),    kColors,    sizeof(kColors),    0);
        transfer.write_buffer(indexBuffer.get(),    kIndices,   sizeof(kIndices),   0);
    }
    ctx->submit();

    // -----------------------------------------------------------------------
    // Per-frame state
    // -----------------------------------------------------------------------
    duk::rhi::PipelineState pipelineState{};
    pipelineState.rasterizer.topology = duk::rhi::PipelineState::Rasterizer::Topology::TRIANGLE_LIST;
    pipelineState.rasterizer.cullMode = duk::rhi::PipelineState::Rasterizer::CullMode::BACK;
    pipelineState.rasterizer.origin = duk::rhi::PipelineState::Rasterizer::Origin::BOTTOM_LEFT;

    const auto matricesSlot   = shaderDataSource.binding_index("matrices");
    const auto colorSlot = shaderDataSource.binding_index("color");

    auto startTime = std::chrono::steady_clock::now();

    // -----------------------------------------------------------------------
    // Main loop
    // -----------------------------------------------------------------------
    window->show();

    while (running) {
        platform->pool_events();

        if (window->minimized() || !window->valid()) {
            continue;
        }

        const auto now     = std::chrono::steady_clock::now();
        const float elapsed = std::chrono::duration<float>(now - startTime).count();

        const auto width  = window->width();
        const auto height = window->height();

        pipelineState.viewport.extent = {static_cast<float>(width), static_cast<float>(height)};
        pipelineState.scissor.extent  = {width, height};

        // Build MVP matrices.
        MatricesUBO ubo{};
        ubo.model = glm::rotate(glm::mat4(1.0f), elapsed * glm::radians(45.0f), glm::vec3(0.0f, 1.0f, 0.0f));
        ubo.model = glm::rotate(ubo.model,         glm::radians(20.0f),          glm::vec3(1.0f, 0.0f, 0.0f));
        ubo.view  = glm::lookAt(
            glm::vec3(0.0f, 2.0f, 4.0f),  // eye
            glm::vec3(0.0f, 0.0f, 0.0f),  // centre
            glm::vec3(0.0f, 1.0f, 0.0f)); // up
        ubo.proj  = glm::perspective(
            glm::radians(45.0f),
            static_cast<float>(width) / static_cast<float>(height),
            0.1f, 100.0f);

        ctx->prepare_present();

        // Upload per-frame UBO.
        {
            auto transfer = ctx->transfer();
            transfer.write_buffer(matricesUBO.get(), &ubo, sizeof(ubo), 0);

            ColorUBO colorUbo{};
            colorUbo.intensity = (glm::sin(elapsed * 2.0f) + 1.0f) * 0.5f;
            transfer.write_buffer(colorUBO.get(), &colorUbo, sizeof(colorUbo), 0);
        }

        // Render pass.
        {
            duk::rhi::RenderBeginParams renderBeginParams;
            renderBeginParams.clearColor = glm::vec4(0.05f, 0.05f, 0.05f, 1.0f);
            renderBeginParams.loadOp     = duk::rhi::LoadOp::CLEAR;
            renderBeginParams.storeOp    = duk::rhi::StoreOp::STORE;

            auto render = ctx->render(renderBeginParams);

            // Bind the uniform buffer at the logical slot resolved by name.
            duk::rhi::ShaderResources resources{};
            resources.bindings[matricesSlot]   = duk::rhi::BufferBinding{matricesUBO.get()};
            resources.bindings[colorSlot] = duk::rhi::BufferBinding{colorUBO.get()};

            render.bind_shader(shader.get(), pipelineState);
            render.bind_resources(resources);

            const duk::rhi::Buffer* vertexBuffers[] = {positionBuffer.get(), colorBuffer.get()};
            render.bind_vertex_buffers(vertexBuffers, 2);
            render.bind_index_buffer(indexBuffer.get());

            duk::rhi::DrawIndexedParams drawParams;
            drawParams.indexCount    = kIndexCount;
            drawParams.firstIndex    = 0;
            drawParams.instanceCount = 1;
            drawParams.firstInstance = 0;
            drawParams.vertexOffset  = 0;

            render.draw_indexed(drawParams);
        }

        ctx->submit();
    }

    return 0;
}

