set(CURRENT_DIR "${DUK_ROOT}/cmake")

include("${CURRENT_DIR}/vcpkg.cmake")
if (DUK_AS_SOURCE)
    message(STATUS "including source duk")
    option(DUK_BUILD_SAMPLE "Disables building of duk_sample" OFF)
    add_subdirectory("${DUK_ROOT}" "${CMAKE_CURRENT_BINARY_DIR}/duk")
else ()
    message(STATUS "including prebuilt duk")
    set(DUK_TOOLCHAIN)
    if (CMAKE_CXX_COMPILER MATCHES "g\\+\\+" OR CMAKE_CXX_COMPILER MATCHES "clang")
        set(DUK_TOOLCHAIN "mingw")
    elseif (MSVC)
        set(DUK_TOOLCHAIN "vs2022")
    else ()
        message(FATAL_ERROR "Failed find a valid duk toolchain for compiler")
    endif ()

    set(DUK_CONFIG_FILE "${DUK_ROOT}/install/${DUK_TOOLCHAIN}/share/duk/duk-config.cmake")

    if (EXISTS "${DUK_CONFIG_FILE}")
        include("${DUK_CONFIG_FILE}")
    else ()
        message(FATAL_ERROR "Could not find duk-config.cmake at \"${DUK_CONFIG_FILE}\", please install duk for toolchain \"${DUK_TOOLCHAIN}\"")
    endif ()
endif ()
