include_guard()

if (CMAKE_GENERATOR MATCHES "Ninja")
    set(VCPKG_TARGET_TRIPLET x64-mingw-dynamic)
endif()

set(X_VCPKG_APPLOCAL_DEPS_INSTALL TRUE CACHE BOOL "Copy dependencies to install target directory")
if (DUK_AS_SOURCE)
    set(DUK_SOURCE_DIR $ENV{DUK_SOURCE_ROOT})
    if (DUK_SOURCE_DIR)
        set(VCPKG_MANIFEST_DIR ${DUK_SOURCE_DIR})
    else ()
        set(VCPKG_MANIFEST_DIR ${CMAKE_SOURCE_DIR})
    endif ()
else ()
    set(VCPKG_MANIFEST_DIR "$ENV{DUK_INSTALL_ROOT}/share/duk")
endif ()
message(STATUS "VCPKG_MANIFEST_DIR: ${VCPKG_MANIFEST_DIR}")
include($ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)
