name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install clang-format 16.0.6
      run: pip install clang-format==16.0.6

    - name: Check formatting
      run: python3 scripts/format.py --check --verbose

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            configure-preset: win-vs
            build-preset: win-vs-release
            test-preset: win-vs
            python: python
          - os: ubuntu-latest
            configure-preset: linux-gcc
            build-preset: linux-gcc-release
            test-preset: linux-gcc
            python: python3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build gcc-14 g++-14 \
          libxcb1-dev libxcb-keysyms1-dev libxcb-icccm4-dev libxcb-cursor-dev \
          libxcb-render0-dev libxcb-render-util0-dev libxcb-image0-dev \
          libxcb-shm0-dev libxcb-util-dev libxcb-randr0-dev

    - name: Setup vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with: { committish: 74e6536215718009aae747d86d84b78376bf9e09 }

    - name: Configure CMake
      run: cmake --preset ${{ matrix.configure-preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.build-preset }}

    - name: Run tests
      run: ctest --preset ${{ matrix.test-preset }}
