# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Windows Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - name: Authenticate private registries
      shell: bash
      run: git config --global credential.https://github.com/duk-studios/vcpkg-registry.helper '!f() { echo username=unused; echo password=${{ secrets.DUK_VCPKG_REGISTRY_PAT }}; }; f'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LLVM & clang-format 16.0.6
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "16.0.6"

    - name: Check formatting
      run: python scripts/format.py --check --verbose

    - name: Setup vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with: { committish: 8d3649ba34aab36914ddd897958599aa0a91b08e }

    - name: Configure CMake
      run: cmake --preset visual-studio

    - name: Build
      run: cmake --build --preset visual-studio-release
